###singUp
# GET  http://localhost:3004/

POST http://localhost:3004/api/v1/shop/signUp
Content-Type: application/json

{ 
    "use": "bangnguyen10",
    "pass": "123123123",
    "email": "bangnguyen794@gmail.com"
}

###exxample
POST http://localhost:3004/v1/api/shop/signout

Content-Type: application/json
{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

